### ISSUE TITLE
Instructions for conversion

### ISSUE THREAD

**Issue by endolith** [YahooTuningGroupsUltimateBackup/YahooTuningGroupsUltimateBackup.github.io#1]
Can you publish the method you used to convert from the archive format to the HTML format?  That would be helpful for other groups.

**Comment by cmloegcmluin** [comment]
Ah! Of course. I didn't realize I hadn't moved the repo I used to *make* this thing under the same organization.

Forgive me, because this is certainly the worst code I've ever written, probably even worse than when I was first starting out, because it didn't occur to me that anyone else would ever use it. But maybe, just maybe, there's something in here that could be of use: https://github.com/YahooTuningGroupsUltimateBackup/YahooTuningGroupsUltimateBackup/blob/master/parser.js

Good luck, and if you have any questions about it, feel free to ask me and I'll try to figure out what I was thinking!!

**Comment by endolith** [comment]
That's ok, all of my code is the worse code I've ever written :)
